- name: demo1
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: PersistentVolumeClaim
        namespace: default
  rules:
    # see !Note sidebar in https://ansible-rulebook.readthedocs.io/en/stable/conditions.html#multiple-conditions-where-all-of-them-have-to-match
    - name: Notify
      condition: |
        (event.type == "ADDED" or event.type == "MODIFIED")
        and
        event.resource.kind == "PersistentVolumeClaim"
        and
        event.resource.status.phase == "Pending"
      action:
        debug:
