- name: demo1
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: PersistentVolumeClaim
        namespace: default
    - sabre1041.eda.k8s:
        api_version: v1
        kind: Pod
        namespace: default
  rules:
    # see !Note sidebar in https://ansible-rulebook.readthedocs.io/en/stable/conditions.html#multiple-conditions-where-all-of-them-have-to-match
    - name: Fix the PersistentVolumeClaim Pod PENDING
      condition:
        all:
          - |
            events.pvc << (
              (event.type == "ADDED" or event.type == "MODIFIED")
              and
              event.resource.kind == "PersistentVolumeClaim"
              and
              event.resource.status.phase == "Pending"
            )
          - |
            events.pod << (
              (event.type == "ADDED" or event.type == "MODIFIED")
              and
              event.resource.kind == "Pod"
              and
              event.resource.status.phase == "Pending"
              and
              event.spec.volumes is selectattr("persistentVolumeClaim.claimName", "==", "task-pv-claim")
            )
        # does not work using the below because of the join with events.pvc.metadata.name
        #     and
        #     event.spec.volumes is selectattr("persistentVolumeClaim.claimName", "==", events.pvc.metadata.name)
        #   )
        # it is also to be noted the "persistentVolumeClaim.claimName" should be working internally,
        # but for some reasons that did not work for me even when hardcoding as:
        #     and
        #     event.spec.volumes is selectattr("persistentVolumeClaim.claimName", "==", "task-pv-claim")
        #   )
        # refer to screenshot in readme for proof :/
      action:
        debug:
          msg:
            - BEGIN *** Fix the PersistentVolumeClaim Pod PENDING ***
            - pvc
            - "{{ events.pvc }}"
            - pod
            - "{{ events.pod }}"
            - END
